package com.github.davidcarboni.restolino.servlet;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.github.davidcarboni.restolino.Api;

/**
 * This is the framework controller.
 * 
 * @author David Carboni
 * 
 */
public class ApiServlet extends HttpServlet {

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 8375590483257379133L;

	@Override
	public void init() throws ServletException {
		Api.init();
	}

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException {
		Api.doGet(request, response);
	}

	@Override
	protected void doPut(HttpServletRequest request,
			HttpServletResponse response) throws ServletException {
		Api.doPut(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException {
		Api.doPost(request, response);
	}

	@Override
	protected void doDelete(HttpServletRequest request,
			HttpServletResponse response) throws ServletException {
		Api.doDelete(request, response);
	}

	@Override
	protected void doOptions(HttpServletRequest request,
			HttpServletResponse response) throws ServletException {
		Api.doOptions(request, response);
	}

}
